services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/Users/Mega Computers/PycharmProjects/Backendpythonprogramming/Day22
    command: uvicorn main:app --host 0.0.0.0 --port 8000
